[tool.poetry]
name = "django-encrypt-decrypt"
version = "1.0.3"
description = "Encrypt and decrypt for django model field."
authors = ["Denis Novikov <alpden550@gmail.com>"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation",
    "Environment :: Web Environment",
    "Framework :: Django :: 3.0",
    "Operating System :: OS Independent",
]
license = "MIT License"
homepage = 'https://github.com/alpden550/django-encrypt-decrypt'
repository = 'https://github.com/alpden550/django-encrypt-decrypt'

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.4"
cryptography = "^3.4.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
