name: ProjectCheck

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Analysing the code with mypy
      run: |
        mypy .
    - name: Test the code pytest
      run: |
        pytest .
    - name: Analysing the code with flake8
      run: |
        pip install flake8
        flake8 --max-line-length=120
